### ISSUE TITLE
Keyboard test

### ISSUE THREAD

**Issue by RayanSp** [Daan645/all-human-wcag-audit#1]
Beschrijf de keyboard test nog iets beter. Je zegt dat het niet duidelijk te zien is waar je bent, maar is het wel mogelijk om over te komen?

**Comment by Daan645** [comment]
OPgelost!: Keyboard test
Als ik op tab drukte en de pijltjes werd er bij veel niet vermeld waar je opstond je hovert over knoppen maar er wordt niet aangegeven dat je er bent door middel van een vierkantje of kleur verandering waardoor dit niet duidelijk is. dit zou opgelost kunnen worden door een animatie of een kleur te geven wanneer een geselecteerd element active is.
